name: Sync Changes to TungaBE

on:
  push:
    branches:
      - backend

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: mwebaze-nicho/hr-system
          ref: backend

      - name: Copy changes to TungaBE backend folder
        run: |
          cp -r * https://github.com/mwebaze-nicho/TungaBE/backend/
          cp -r .github https://github.com/mwebaze-nicho/TungaBE/backend/

